imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ObladyZuulBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%
        types:
            json: Sonata\Doctrine\Types\JsonType 
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
            default:
                mappings:
                    ObladyZuulBundle: ~
                    SonataUserBundle: ~
                    FOSUserBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }
    
sonata_block:
    default_contexts: [cms]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]
        
        sonata.block.service.text:
        sonata.block.service.rss:            
            
sonata_admin:
    templates:
     #   dashboard: ObladyZuulBundle:Sonata:dashboard.html.twig
     #   layout:   ObladyZuulBundle:Sonata:standard_layout.html.twig
    assets:
        javascripts:
             - bundles/sonataadmin/vendor/jquery/dist/jquery.min.js 
             - bundles/sonatacore/vendor/moment/min/moment.min.js 
             - bundles/sonataadmin/vendor/jqueryui/ui/minified/jquery-ui.min.js
             - bundles/sonataadmin/vendor/jqueryui/ui/minified/i18n/jquery-ui-i18n.min.js
             - bundles/sonataadmin/vendor/bootstrap/dist/js/bootstrap.min.js
             - bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js
             - bundles/sonataadmin/jquery/jquery.form.js
             - bundles/sonataadmin/jquery/jquery.confirmExit.js
             - bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/js/bootstrap-editable.min.js
             - bundles/sonataadmin/vendor/select2/select2.min.js
             - bundles/sonataadmin/App.js
             - bundles/sonataadmin/Admin.js
        stylesheets:
            - bundles/sonataadmin/vendor/bootstrap/dist/css/bootstrap.min.css
            #- bundles/sonataadmin/vendor/AdminLTE/css/font-awesome.min.css
            - //netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css
            - bundles/sonataadmin/vendor/AdminLTE/css/ionicons.min.css
            - bundles/sonataadmin/vendor/AdminLTE/css/AdminLTE.css
            - bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css
            - bundles/sonataadmin/vendor/jqueryui/themes/base/jquery-ui.css
            - bundles/sonataadmin/vendor/select2/select2.css
            - bundles/sonataadmin/vendor/select2/select2-bootstrap.css
            - bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css
            - bundles/sonataadmin/css/styles.css
            - bundles/sonataadmin/css/layout.css            
            

    dashboard:
        blocks: ~

fos_user:
    db_driver:      orm # can be orm or odm
    firewall_name:  main
    user_class:     Oblady\ZuulBundle\Entity\User

    group:
        group_class: Oblady\ZuulBundle\Entity\Group    
        group_manager: sonata.user.orm.group_manager
    service:
        user_manager: sonata.user.orm.user_manager         
    profile:  # Profile Form (firstname, lastname, etc ...)
        form:
            type:               sonata_user_profile
            handler:            sonata.user.profile.form.handler.default
            name:               sonata_user_profile_form
            validation_groups:  [Profile]            
sonata_user:
    security_acl: true
    manager_type: orm # can be orm or mongodb    
    class:
        user:               Oblady\ZuulBundle\Entity\User
        group:              Oblady\ZuulBundle\Entity\Group
    
bcc_resque:
    class: BCC\ResqueBundle\Resque           # the resque class if different from default
    vendor_dir: %kernel.root_dir%/../vendor  # the vendor dir if different from default
#   prefix: zuul                 # optional prefix to separate Resque data per site/app
    redis:
        host: localhost                      # the redis host
        port: 6379                           # the redis port
        database: 0                          # the redis database    
        
    
avalanche_imagine:
    filters:
        dashelement:
            type:    thumbnail
            options: { size: [120, 120], mode: outbound }
            
          