<?php

namespace Oblady\ZuulBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClusterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClusterRepository extends EntityRepository
{

    public function findAll()
    {
        return $this->findBy(array(), array('name'=>'asc'));  
    }
}
