<?php

namespace Oblady\ZuulBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
* ServerRepository
*
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
*/
class KeyRepository extends EntityRepository
{
    
    
    
}

