<?php

namespace Oblady\ZuulBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ServerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServerRepository extends EntityRepository {

    public function findByClusterId($clusterId) {

        $qb = $this->_em->createQueryBuilder()
                ->select('s')
                ->from($this->_entityName, 's', 's.id')
                ->leftJoin('s.clusters', 'c')
                ->where('c.id = :cluser_id ')
                ->setParameter('cluser_id', (int) $clusterId);

        return $qb->getQuery()
                        ->getResult();
    }

    public function findAllIndexed() {

        $qb = $this->_em->createQueryBuilder()
                ->select('s')
                ->from($this->_entityName, 's', 's.id')
        ;

        return $qb->getQuery()
                        ->getResult();
    }

    public function findAll() {
        return $this->findBy(array(), array('name' => 'asc'));
    }

}
