<?php

namespace Oblady\ZuulBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

    public function findAll()
    {
        return $this->findBy(array(), array('username'=>'asc'));  
    }
}
